module.exports.SETSELLERS = "SELLER_SETSELLERS"
module.exports.SETDEBUG = "SELLER_SETDEBUG"

module.exports.ADDTAB = "SELLER_ADDTAB"
module.exports.SWITCHTAB = "SELLER_SWITCHTAB"
module.exports.DELETETAB = "SELLER_DELETETAB"
module.exports.CLOSETABS = "SELLER_CLOSETABS"

module.exports.NATIVE_PRINTER = "SELLER_NATIVE_PRINTER"
module.exports.LISTEN_SCANNER = "SELLER_LISTEN_SCANNER"
module.exports.ADD_TOAST = 'SELLER_ADD_TOAST'
module.exports.REMOVE_TOAST = 'SELLER_REMOVE_TOAST'
module.exports.CLEAR_TOASTS = 'SELLER_CLEAR_TOASTS'
