module.exports.STATUS_TYPES = {
	STAGE_TYPING: "STAGE_TYPING",
	STAGE_ADDED: "STAGE_ADDED",
	COMMIT_BEGIN: "COMMIT_BEGIN",
	COMMIT_TYPING: "COMMIT_TYPING",
	COMMIT_END: "COMMIT_END"
}

module.exports.SETSTATUS = "CUSTOMER_STATUS"
module.exports.SETPAID = "CUSTOMER_PAID"
module.exports.SETSELLER = "CUSTOMER_SELLER"
module.exports.SETDATE = "CUSTOMER_SETDATE"